<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "little_library"
 *
 * Auto generated by Extension Builder 2015-05-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Little Library',
	'description' => 'An extension to manage little libraries.',
	'category' => 'plugin',
	'author' => 'Valentin Funk',
	'author_email' => 'valentin.funk@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);